
PLAY [First NASA APOD playbook] ************************************************

TASK [Lookup the NASA APOD API for 2019-01-01 in std def] **********************
[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/home/student/apod.png'[0m
[0;31mfatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.rzfeeser.nasa_api.plugins.modules.nasa_apod', init_globals=dict(_module_fqn='ansible_collections.rzfeeser.nasa_api.plugins.modules.nasa_apod', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\", line 161, in <module>\n  File \"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\", line 158, in main\n  File \"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\", line 147, in run_module\nFileNotFoundError: [Errno 2] No such file or directory: '/home/student/apod.png'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}[0m

PLAY RECAP *********************************************************************
[0;31mlocalhost[0m                  : ok=0    changed=0    unreachable=0    [0;31mfailed=1   [0m skipped=0    rescued=0    ignored=0   
